[package]
name = "timely-window"
version = "0.1.0"
edition = "2021"
authors = ["ZhengYu, Xu <zen-xu@outlook.com>"]

[dependencies]
timely = { git = "https://github.com/TimelyDataflow/timely-dataflow", default-features = false, features = [
    "bincode",
] }
